name = "github-asana-issue-sync"
main = "src/index.js"
compatibility_date = "2024-11-01"
logpush = true

[observability]
enabled = true

[env.production]
vars = {}

[env.production.secrets]
# Set these in Cloudflare dashboard or with wrangler secret put
# ASANA_PAT = "your_asana_personal_access_token"
# ASANA_PROJECT_ID = "your_asana_project_id"
# REPOSITORY_FIELD_ID = "optional_custom_field_id_for_repository"
# CREATOR_FIELD_ID = "optional_custom_field_id_for_creator"
# GITHUB_URL_FIELD_ID = "optional_custom_field_id_for_github_url"
# GITHUB_TOKEN = "optional_github_token_for_api_calls"
# WEBHOOK_SECRET = "github_webhook_secret_for_verification"